### ISSUE TITLE
Top-level documentation?

### ISSUE THREAD

**Issue by rrthomas** [AmaiKinono/citre#36]
I just took a look at citre, it seems good! I used it with `anjuta-tags` to navigate Vala code.

So far, I was able to install it, and get `citre-jump` to work, also xref-integration. Great!

It would be good to see citre packaged for MELPA, and with some basic top-level documentation in the package description and in a `README.md` file, to help users get started. Are you planning that?

Thanks for working on citre!

**Comment by AmaiKinono** [comment]
Glad to hear it works for you ;)

> I used it with `anjuta-tags` to navigate Vala code.

Sounds like you are working on some GTK project? I also have an interest in GTK but haven't begin my study on it.

> and get `citre-jump` to work, also xref-integration.

I know you mainly focus on xref, but these two are not the best tools in my opinion. They are only for users who are used to similar tools and don't want to change. I'd recommend you try `citre-peek`, it's much more powerful and slick.

> It would be good to see citre packaged for MELPA, and with some basic top-level documentation in the package description and in a `README.md` file, to help users get started. Are you planning that?

I have plan for that. However Citre is still under heavy construction. I am still experimenting on the design of the tools, so it's not the best time to write documentation and publish the package now. I think we can get things down in 2021. See also https://github.com/AmaiKinono/citre/milestone/1 and the wiki.

**Comment by rrthomas** [comment]
Thanks for your quick response!

> Sounds like you are working on some GTK project? I also have an interest in GTK but haven't begin my study on it.

No, this is for GNU Zile, a simple terminal-only Emacs clone. I have rewritten it in Vala from C.

> I know you mainly focus on xref, but these two are not the best tools in my opinion. They are only for users who are used to similar tools and don't want to change. I'd recommend you try `citre-peek`, it's much more powerful and slick.

I look forward to trying that when I have more time, but for now I'd just like something that works the same as xref everywhere else.

> I have plan for that. However Citre is still under heavy construction. I am still experimenting on the design of the tools, so it's not the best time to write documentation and publish the package now.

Sounds good! However, you still might want to consider publishing on MELPA (unstable) for early adopters, as that might get you useful feedback for your continued development. I'm sure I can't be the only Emacs user who would like ctags support!

**Comment by AmaiKinono** [comment]
> However, you still might want to consider publishing on MELPA (unstable) for early adopters, as that might get you useful feedback for your continued development.

Thanks for the advice. I have limited experience using MELPA (I use git-based Emacs package manager now), but I think the stable/unstable version are not much different... melpa-stable just publishes the tagged versions, it's nothing like "debian-stable" where the dependency problem is actually considered. Also, I don't think people are actually okay with packages in melpa-unstable to actually being unstable, changing its design and breaking their configurations from time to time.

Could I close this for now? The 2 things you care about (MELPA and docs) are added to #21.

**Comment by AmaiKinono** [comment]
Oh, and, if you have any questions on using Citre that may not be suitable for a issue, you can email me (my email is in the code).

**Comment by rrthomas** [comment]
Sure, please close this issue! Looking in MELPA (unstable) there are plenty of packages that are indeed unstable. You can always say at the top of the description "This package is under heavy development! Interfaces may change or break!".
