### ISSUE TITLE
Turning on citre-mode in dired-mode

### ISSUE THREAD

**Issue by masatake** [AmaiKinono/citre#43]
u-ctags can record included C header files as reference tags to a tags file 
If we can use citre-mode in dired-mode buffers, we can list "which source files includes foo.h" with pressing M-. on "foo.h", a dried entry.

**Comment by AmaiKinono** [comment]
Good idea ;) But maybe I can't work it out soon.

The key is to modify the mechanism to grab the symbol under point. Now it won't work for file names that have dots in them.

The simple way is to grab the active region if there's one, so you can mark the filename first and find it's definition. It may not be convenient to use, but good to have anyway in case the simple "symbol under point" doesn't grab the symbol you want.

The right way is to extend the concept of "symbol" into a specific data structure. I intend to do this when I implement language-specific support mechanism. The extended "symbol" should contain every bit of information that's useful for filtering/sorting, and the language support implementation decides how to make use of those information.

Once this is implemented, of course we could offer specific `dired-mode` support, where we:

- Grab the whole filename as symbol.
- Filter only reference tags, or maybe add other filter/sort rules.
