### ISSUE TITLE
Jump to C source file from a Makefile

### ISSUE THREAD

**Issue by masatake** [AmaiKinono/citre#50]
In `linux/arch/x86/kernel/apic/Makefile`, I gave Emacs "C-u M-.", and "hw_nmi.c".
citre doesn't take me to the C file.

When using readtags directly, I got
```
$ readtags -e hw_nmi.c
hw_nmi.c	arch/x86/kernel/apic/hw_nmi.c	1;"	kind:F
```

I extracted the filter expression used in the above process with strace.
```scheme
(not (or
      (and $extras ((string->regexp "(^|,) ?(anonymous inputFile)(,|$)" :case-fold false) $extras))
      (and $kind ((string->regexp "^(file|F)$" :case-fold false) $kind))
      ))
```
For me, this filter expression avoiding F kind is too *strong*.

**Comment by AmaiKinono** [comment]
Thanks for report. Please reopen/comment if there are still problems.

**Comment by masatake** [comment]
Works well. Thank you.
