### ISSUE TITLE
Peek window in *xref* buffer

### ISSUE THREAD

**Issue by masatake** [AmaiKinono/citre#51]
I want the peek window to show the definition for the language object under the point at *xref* buffer
*xref* shows only one line pattern for each language object.  In some cases, showing only one line is not enough when choosing one of the definitions for the language object.

*xref* buffer:
```
/home/jet/var/linux/arch/x86/events/perf_event.h
661: (member) int		apic;
/home/jet/var/linux/arch/x86/include/asm/apic.h
364: (externvar) extern struct apic *apic;
290: (struct) struct apic {
/home/jet/var/linux/arch/x86/include/asm/kvm_host.h
545: (member/kvm_vcpu_arch::kvm_lapic) struct kvm_lapic *apic;    /* kernel irqchip context */
/home/jet/var/linux/arch/x86/kernel/apic/apic_flat_64.c
23: (variable/apic) struct apic *apic __ro_after_init = &apic_flat;
/home/jet/var/linux/arch/x86/kernel/apic/probe_32.c
116: (variable/apic) struct apic *apic __ro_after_init = &apic_default;
```

If the point is at apic of `290: (struct) struct apic {`, I expect the peek window to show the definition of the struct as the first candidate.

**Comment by AmaiKinono** [comment]
Thanks for the idea! Please reopen/comment if there are still problems.

**Comment by masatake** [comment]
Works well! Thank you.
